services:
  postgres-db:
    image: postgres:15-alpine
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: usr123
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"

  spring-fintech-platform:
    build: .
    container_name: my-spring-boot-app
    depends_on:
      - postgres-db

    ports:
      - "8080:8080"
    network_mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=dev
